name: build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.0"   # pin => pas de "channel: stable"

      - name: Flutter pub get (with cache)
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - run: flutter pub get

      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons:main

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: duduf-occas-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
